lua54 main.lua < tests/test1.txt
lua54 main.lua < tests/test2.txt
lua54 main.lua < tests/test3.txt
lua54 main.lua < tests/test4.txt
lua54 main.lua < tests/test5.txt
lua54 main.lua < tests/test6.txt
lua54 main.lua < tests/test7.txt
lua54 main.lua < tests/test8.txt
lua54 main.lua < tests/test9.txt
lua54 main.lua < tests/test10.txt
lua54 main.lua < tests/test11.txt
lua54 main.lua < tests/test12.txt